### ISSUE TITLE
Why separate Future and Promise?

### ISSUE THREAD

**Issue by onmyway133** [couchdeveloper/FutureLib#1]
What is the motivation behind separating Future and Promise? I see that FutureLib uses Promise for fulfilling and Future for continuation? Is it worth the separation?

**Comment by couchdeveloper** [comment]
Future & Promise strive to solve the problem to transfer the result of a task from one thread (execution context) to the other.  (Note, that the result can be either a value or an error)

The task that calculates the result eventually needs to send its result to "some object".  On the other end, the consumer of the task's result need to obtain that result as well from "some object". Now, suppose these objects are the same, that is there is actually only one object. Now, the question arises, who will _own_ this object? Note, that a future also owns all continuations which have been registered by the consumer.

Now suppose, the consumer want's to abandon its interest in the result before the task has been finished. The task knows nothing about this event. If the "object" will be shared and still owned by the task, this "object" won't be deallocated, and its continuations will stay there as well. That means, the consumer's registered continuations will run anyway (unless the consumer "unregisters" them manually somehow - but there's not API for this). Even more, those continuations may also hold a reference to the consumer itself, and that would mean, that the consumer will not be deallocated before the task finished and the continuations have been run.

On the other hand, a task may run into trouble and abort prematurely - without completing the promise. If the "object" will be shared, it will not be deallocated when the task get deallocated: the shared object just gets "unlinked" from the task when the task gets destroyed - the single "object" will be still shared by consumers. Since this abort situation is not handled by fulfilling or rejecting the promise through some error handler that will be invoked by the task, the future will _never_ be completed. This will violate the rule that a future must be eventually completed.

If, however, there are two distinct objects - which communicate over a _shared internal object_ - all these situations can be handled gracefully. For example, in FutureLib, the Promise will be owned solely by the task. When a Promise will be created (by the task) it internally also creates its "associated" Future. When the future has been obtained by the consumer, the Promise subsequently holds this future through a _weak_ reference. So, once a consumer has acquired the future, there is only one strong reference which is hold by the consumer of the future. This future can now be shared by other consumers through a strong reference. But notice, that the promise does not hold a strong reference to this future.

Now, suppose the task will be aborted and deallocated before it has a chance to complete its promise: Since the promise will be owned solely by the task, it also gets deallocated with the task. In its deinitialization routine the promise can complete its associated future with an error, e.g.: "Broken promise" or such.

Now, suppose all consumers prematurely abandon their interest in the result and release this future before it has been completed, the future will be deallocated and with it all their continuations, regardless of their state - and without affecting the promise. If the task later fulfills its promise, the promise will (eventually) notice that the future doesn't exist anymore - but nonetheless, the promise still exists. Additionally, in FutureLib, the promise has means to get notified _when_ its associated future gets destroyed and can call a callback. This callback can be set by the task, which - for example - cancels the task - since there is obviously nobody anymore interested in the result.

Another aspect is separating the interface into two parts: one suitable for the producer of the result, and one suitable for the consumer. This makes sense, since a producer won't need to read its future's result. On the other hand, it makes no sense to allow a consumer to complete a future. Completing the future is the sole responsibility of the task.

That's the reason why there are two separate objects: Promise and Future.

**Comment by onmyway133** [comment]
@couchdeveloper got it, many thanks for such detail answer

**Comment by couchdeveloper** [comment]
You're welcome - I know you'll do the same for someone else. ;)
